---

- name: 'Include OS-specific variables'
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_system }}.yml"

- name: 'Include OS-specific installation steps'
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_system }}/main.yml"
    - "unsupported.yml"