---

- name: 'apt : Add InfluxData apt signing key'
  apt_key:
    url: 'https://repos.influxdata.com/influxdb.key'
    id: 2582E0C5
    state: present

- name: 'apt : Add Telegraf repository'
  apt_repository:
    repo: 'deb https://repos.influxdata.com/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable'
    filename: 'telegraf'
    state: present

- name: 'apt : Install Telegraf package via apt'
  apt:
    name: telegraf